package com.xover.music.application.network;

public enum MessageType {
    PLAYLIST_UPDATED,
    TRACK_SELECTED,
    TRACK_READY,
    TRACK_FAILED,
    PLAY_AT,
    PAUSE,
    SEEK,
    TIME_SYNC_REQUEST,
    TIME_SYNC_RESPONSE,
    ROOM_CONTROL_PERMISSION,
    PLAYLIST_ADD_REQUEST,
    PLAYLIST_REMOVE_REQUEST,
    PLAYLIST_MOVE_REQUEST,
    PLAYLIST_RENAME_REQUEST,
    PLAYLIST_SELECT_REQUEST,
    PLAY_REQUEST,
    PAUSE_REQUEST,
    SEEK_REQUEST,
    NEXT_TRACK_REQUEST,
    BACK_TRACK_REQUEST
}
