package com.xover.music.application.network;

public enum MessageType {
    PLAYLIST_UPDATED,
    TRACK_SELECTED,
    TRACK_READY,
    TRACK_FAILED,
    PLAY_AT,
    PAUSE,
    SEEK,
    TIME_SYNC_REQUEST,
    TIME_SYNC_RESPONSE,
    PLAYLIST_EDIT_PERMISSION,
    PLAYLIST_ADD_REQUEST,
    PLAYLIST_REMOVE_REQUEST,
    PLAYLIST_MOVE_REQUEST,
    PLAYLIST_RENAME_REQUEST,
    PLAYLIST_SELECT_REQUEST
}
